
              require("catppuccin").setup({
                flavour = "mocha",
                transparent_background = true,
                color_overrides = {
                  mocha = {
                    rosewater = "#ddc7a1",
                    flamingo  = "#ea6962",
                    pink      = "#7daea3",
                    mauve     = "#e78a4e",
                    red       = "#c14a4a",
                    maroon    = "#e78a4e",
                    peach     = "#d3869b",
                    yellow    = "#d4be98",
                    green     = "#a9b665",
                    teal      = "#89b482",
                    sky       = "#a9b665",
                    sapphire  = "#458588",
                    blue      = "#7daea3",
                    lavender  = "#7daea3",
                    text      = "#d4be98",
                    subtext1  = "#458588",
                    subtext0  = "#928374",
                    overlay2  = "#928374",
                    overlay1  = "#7c6f64",
                    overlay0  = "#665c54",
                    surface2  = "#504945",
                    surface1  = "#458588",
                    surface0  = "#32302f",
                    base      = "#1d2021",
                    mantle    = "#141414",
                    crust     = "#141414",
                  },
                },
                integrations = {
                  enabled = true,
                  nvimtree = {
                    transparent_panel = true,
                    show_root = true,
                  },

                  hop = true,
                  gitsigns = true,
                  telescope = true,
                  treesitter = true,
                  treesitter_context = true,
                  ts_rainbow = true,
                  fidget = true,
                  alpha = true,
                  leap = true,
                  lsp_saga = true,
                  markdown = true,
                  noice = true,
                  notify = true,
                  which_key = true,
                  navic = {
                    enabled = true,
                    custom_bg = "none",
                  },
                  aerial = true,
                  cmp = true,
                  dashboard = true,
                  flash = true,
                  headlines = true,
                  illuminate = true,
                  indent_blankline = { enabled = true },
                  lsp_trouble = true,
                  mason = true,
                  mini = true,
                  native_lsp = {
                    enabled = true,
                    underlines = {
                      errors = { "undercurl" },
                      hints = { "undercurl" },
                      warnings = { "undercurl" },
                      information = { "undercurl" },
                    },
                  },
                  neotest = true,
                  neotree = true,
                  semantic_tokens = true,
                },
              })
              vim.cmd.colorscheme("catppuccin")
